### PR TITLE
Hacktober 2020

### PR DESCRIPTION
**Pull request by navya252001**
I have made changes to the read me
Check it and tell me if you need improvmenet

### CODE REVIEW

**Comment by amanjagdev** [comment]
Great work @navya252001 ...
I am really happy with how it came out 👍

**Comment by navya252001** [comment]
Sir please help me in HACKTOBER FEST 2020
We will honor all valid pull requests prior to this change, and as of October 3, 2020 at 12:00:00 UTC – and October 3 in all time zones – pull requests will only count toward earning a T-shirt or planting a tree if they are submitted in a repository classified with the ‘hacktoberfest’ topic. The pull requests will also need to be merged, approved by a maintainer, or labeled as ‘hacktoberfest-accepted’ in order to qualify. The deadline for completions, merging, labeling, and approving is November 1.
Latest guidelines issued by the organizers
I sincerely hope you will help me
I have already submitted a pull request
https://hacktoberfest.digitalocean.com/hacktoberfest-update
I am attaching the link too for your convenience

**Comment by amanjagdev** [comment]
@navya252001  I have already merged your PR before Oct 3, 2020, 12:00:00 UTC.
So I don't think so we need to change anything if you still feel that there are somethings to be taken care of, feel free to ping me here or on the links in my GitHub 😄

**Comment by navya252001** [comment]
Okay

**Comment by amanjagdev** [comment]
I have added "hactoberfest" topic in the repository which was necessary.

**Pull request merged**
